apiVersion: v1
data:
  LOG_LEVEL: ZGVidWc=
  NEW_RELIC_APP_NAME: Y29sb21ib3N0aXBz
  NEW_RELIC_LICENSE_KEY: ZjlhZGU5Mjc1OGYyYWJhNjZhNjliYWI4Mjk4MjQzYTc2N2NlTlJBTA==
  PORT: ODA4MA==
kind: Secret
metadata:
  creationTimestamp: null
  name: server-secrets
  namespace: colombostips
