apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: server
  name: server
  namespace: colombostips 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - image: eduardobcolombo/server:1.0
        name: server
        ports:
          - containerPort: 8080
        resources:
          requests:
            memory: 64Mi
          limits:
            memory: 256Mi          
        envFrom:
          - secretRef:
              name: server-secrets
